@startuml
annotation java.lang.Override
annotation java.lang.SuppressWarnings
annotation javafx.fxml.FXML
class it.unisa.java_music_playlist_manager.App
class it.unisa.java_music_playlist_manager.PrimaryViewController
class it.unisa.java_music_playlist_manager.model.Library
class it.unisa.java_music_playlist_manager.model.PausedState
class it.unisa.java_music_playlist_manager.model.PlaybackManager
class it.unisa.java_music_playlist_manager.model.PlayingState
class it.unisa.java_music_playlist_manager.model.Playlist
class it.unisa.java_music_playlist_manager.model.SequentialStrategy
class it.unisa.java_music_playlist_manager.model.StoppedState
class it.unisa.java_music_playlist_manager.model.Track
class java.io.IOException
class java.time.LocalDate
class java.util.ArrayList
class java.util.List
class java.util.Objects
class java.util.Optional
class java.util.UUID
class javafx.application.Application
class javafx.collections.FXCollections
class javafx.collections.ObservableList
class javafx.fxml.FXMLLoader
class javafx.scene.Parent
class javafx.scene.Scene
class javafx.scene.control.Alert
class javafx.scene.control.Button
class javafx.scene.control.ButtonType
class javafx.scene.control.ChoiceDialog
class javafx.scene.control.ComboBox
class javafx.scene.control.ContextMenu
class javafx.scene.control.Label
class javafx.scene.control.MenuItem
class javafx.scene.control.Slider
class javafx.scene.control.TableColumn
class javafx.scene.control.TableView
class javafx.scene.control.TextField
class javafx.scene.control.TextInputDialog
class javafx.scene.control.cell.PropertyValueFactory
class javafx.scene.image.Image
class javafx.scene.image.ImageView
class javafx.scene.layout.HBox
class javafx.stage.Modality
class javafx.stage.Stage
interface it.unisa.java_music_playlist_manager.model.Observer
interface it.unisa.java_music_playlist_manager.model.PlaybackState
interface it.unisa.java_music_playlist_manager.model.PlaybackStrategy
interface it.unisa.java_music_playlist_manager.model.Subject
it.unisa.java_music_playlist_manager.App ..> java.lang.Override
it.unisa.java_music_playlist_manager.App ..> java.io.IOException
it.unisa.java_music_playlist_manager.App --|> javafx.application.Application
it.unisa.java_music_playlist_manager.App ..> javafx.fxml.FXMLLoader
it.unisa.java_music_playlist_manager.App ..> javafx.scene.Parent
it.unisa.java_music_playlist_manager.App ..> javafx.scene.Scene
it.unisa.java_music_playlist_manager.App ..> javafx.scene.image.Image
it.unisa.java_music_playlist_manager.App ..> javafx.stage.Stage
it.unisa.java_music_playlist_manager.PrimaryViewController ..> java.lang.Override
it.unisa.java_music_playlist_manager.PrimaryViewController ..> java.lang.SuppressWarnings
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.fxml.FXML
it.unisa.java_music_playlist_manager.PrimaryViewController ..> it.unisa.java_music_playlist_manager.model.Library
it.unisa.java_music_playlist_manager.PrimaryViewController ..> it.unisa.java_music_playlist_manager.model.PlaybackManager
it.unisa.java_music_playlist_manager.PrimaryViewController ..> it.unisa.java_music_playlist_manager.model.Playlist
it.unisa.java_music_playlist_manager.PrimaryViewController ..> it.unisa.java_music_playlist_manager.model.Track
it.unisa.java_music_playlist_manager.PrimaryViewController ..> java.util.List
it.unisa.java_music_playlist_manager.PrimaryViewController ..> java.util.Optional
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.collections.FXCollections
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.collections.ObservableList
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.fxml.FXMLLoader
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.Parent
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.Scene
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.Alert
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.Button
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.ButtonType
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.ChoiceDialog
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.ComboBox
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.ContextMenu
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.Label
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.MenuItem
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.Slider
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.TableColumn
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.TableView
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.TextField
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.TextInputDialog
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.cell.PropertyValueFactory
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.image.ImageView
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.layout.HBox
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.stage.Modality
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.stage.Stage
it.unisa.java_music_playlist_manager.PrimaryViewController --|> it.unisa.java_music_playlist_manager.model.Observer
it.unisa.java_music_playlist_manager.model.Library ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.Library ..> java.util.ArrayList
it.unisa.java_music_playlist_manager.model.Library ..> java.util.List
it.unisa.java_music_playlist_manager.model.Library --|> it.unisa.java_music_playlist_manager.model.Subject
it.unisa.java_music_playlist_manager.model.PausedState ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.PausedState --|> it.unisa.java_music_playlist_manager.model.PlaybackState
it.unisa.java_music_playlist_manager.model.PlaybackManager ..> java.util.ArrayList
it.unisa.java_music_playlist_manager.model.PlaybackManager ..> java.util.List
it.unisa.java_music_playlist_manager.model.PlayingState ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.PlayingState --|> it.unisa.java_music_playlist_manager.model.PlaybackState
it.unisa.java_music_playlist_manager.model.Playlist ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.Playlist ..> java.util.ArrayList
it.unisa.java_music_playlist_manager.model.Playlist ..> java.util.List
it.unisa.java_music_playlist_manager.model.Playlist ..> java.util.Objects
it.unisa.java_music_playlist_manager.model.Playlist ..> java.util.UUID
it.unisa.java_music_playlist_manager.model.SequentialStrategy ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.SequentialStrategy --|> it.unisa.java_music_playlist_manager.model.PlaybackStrategy
it.unisa.java_music_playlist_manager.model.StoppedState ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.StoppedState --|> it.unisa.java_music_playlist_manager.model.PlaybackState
it.unisa.java_music_playlist_manager.model.Track ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.Track ..> java.time.LocalDate
it.unisa.java_music_playlist_manager.model.Track ..> java.util.ArrayList
it.unisa.java_music_playlist_manager.model.Track ..> java.util.List
it.unisa.java_music_playlist_manager.model.Track ..> java.util.Objects
it.unisa.java_music_playlist_manager.model.Track ..> java.util.UUID
it.unisa.java_music_playlist_manager.model.Track --|> it.unisa.java_music_playlist_manager.model.Subject
@enduml