@startuml
abstract class it.unisa.java_music_playlist_manager.model.Playlist
abstract class it.unisa.java_music_playlist_manager.model.PlaylistGenerator
annotation java.lang.Override
annotation java.lang.SuppressWarnings
annotation javafx.fxml.FXML
class it.unisa.java_music_playlist_manager.AddTrackController
class it.unisa.java_music_playlist_manager.App
class it.unisa.java_music_playlist_manager.HomeController
class it.unisa.java_music_playlist_manager.PlayerController
class it.unisa.java_music_playlist_manager.PrimaryViewController
class it.unisa.java_music_playlist_manager.SidebarController
class it.unisa.java_music_playlist_manager.model.AutomaticPlaylistByGenre
class it.unisa.java_music_playlist_manager.model.AutomaticPlaylistByTag
class it.unisa.java_music_playlist_manager.model.AutomaticPlaylistByYear
class it.unisa.java_music_playlist_manager.model.AutomaticPlaylistGenerator
class it.unisa.java_music_playlist_manager.model.Library
class it.unisa.java_music_playlist_manager.model.ManualPlaylist
class it.unisa.java_music_playlist_manager.model.ManualPlaylistGenerator
class it.unisa.java_music_playlist_manager.model.PausedState
class it.unisa.java_music_playlist_manager.model.PlaybackManager
class it.unisa.java_music_playlist_manager.model.PlayingState
class it.unisa.java_music_playlist_manager.model.RepeatStrategy
class it.unisa.java_music_playlist_manager.model.RepeatTrackStrategy
class it.unisa.java_music_playlist_manager.model.SequentialStrategy
class it.unisa.java_music_playlist_manager.model.ShuffleStrategy
class it.unisa.java_music_playlist_manager.model.StoppedState
class it.unisa.java_music_playlist_manager.model.Track
class java.io.File
class java.io.IOException
class java.time.LocalDate
class java.util.ArrayList
class java.util.Collections
class java.util.Comparator
class java.util.HashSet
class java.util.LinkedHashSet
class java.util.List
class java.util.Locale
class java.util.Objects
class java.util.Optional
class java.util.Set
class java.util.UUID
class java.util.function.Consumer
class java.util.stream.Collectors
class javafx.application.Application
class javafx.application.Platform
class javafx.beans.property.SimpleIntegerProperty
class javafx.beans.property.SimpleStringProperty
class javafx.collections.FXCollections
class javafx.collections.MapChangeListener
class javafx.collections.ObservableList
class javafx.fxml.FXMLLoader
class javafx.scene.Node
class javafx.scene.Parent
class javafx.scene.Scene
class javafx.scene.control.Alert
class javafx.scene.control.Button
class javafx.scene.control.ButtonType
class javafx.scene.control.ChoiceDialog
class javafx.scene.control.ComboBox
class javafx.scene.control.ContextMenu
class javafx.scene.control.Label
class javafx.scene.control.ListCell
class javafx.scene.control.ListView
class javafx.scene.control.MenuItem
class javafx.scene.control.ScrollPane
class javafx.scene.control.Slider
class javafx.scene.control.TableCell
class javafx.scene.control.TableColumn
class javafx.scene.control.TableView
class javafx.scene.control.TextField
class javafx.scene.control.TextInputDialog
class javafx.scene.control.Tooltip
class javafx.scene.image.Image
class javafx.scene.image.ImageView
class javafx.scene.layout.HBox
class javafx.scene.layout.VBox
class javafx.scene.media.Media
class javafx.scene.media.MediaPlayer
class javafx.stage.FileChooser
class javafx.stage.Modality
class javafx.stage.Stage
class javafx.util.Duration
class org.controlsfx.control.CheckComboBox
enum it.unisa.java_music_playlist_manager.model.TagPredefined
interface it.unisa.java_music_playlist_manager.model.Observer
interface it.unisa.java_music_playlist_manager.model.Playable
interface it.unisa.java_music_playlist_manager.model.PlaybackState
interface it.unisa.java_music_playlist_manager.model.PlaybackStrategy
interface it.unisa.java_music_playlist_manager.model.Subject
interface it.unisa.java_music_playlist_manager.model.Tag
it.unisa.java_music_playlist_manager.model.Playlist ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.Playlist ..> java.util.List
it.unisa.java_music_playlist_manager.model.Playlist ..> java.util.Objects
it.unisa.java_music_playlist_manager.model.Playlist ..> java.util.UUID
it.unisa.java_music_playlist_manager.model.Playlist --|> it.unisa.java_music_playlist_manager.model.Playable
it.unisa.java_music_playlist_manager.AddTrackController ..> javafx.fxml.FXML
it.unisa.java_music_playlist_manager.AddTrackController ..> it.unisa.java_music_playlist_manager.model.Library
it.unisa.java_music_playlist_manager.AddTrackController ..> it.unisa.java_music_playlist_manager.model.Track
it.unisa.java_music_playlist_manager.AddTrackController ..> java.io.File
it.unisa.java_music_playlist_manager.AddTrackController ..> java.util.List
it.unisa.java_music_playlist_manager.AddTrackController ..> javafx.application.Platform
it.unisa.java_music_playlist_manager.AddTrackController ..> javafx.collections.MapChangeListener
it.unisa.java_music_playlist_manager.AddTrackController ..> javafx.scene.control.Button
it.unisa.java_music_playlist_manager.AddTrackController ..> javafx.scene.control.ComboBox
it.unisa.java_music_playlist_manager.AddTrackController ..> javafx.scene.control.Label
it.unisa.java_music_playlist_manager.AddTrackController ..> javafx.scene.control.TextField
it.unisa.java_music_playlist_manager.AddTrackController ..> javafx.scene.layout.VBox
it.unisa.java_music_playlist_manager.AddTrackController ..> javafx.scene.media.Media
it.unisa.java_music_playlist_manager.AddTrackController ..> javafx.scene.media.MediaPlayer
it.unisa.java_music_playlist_manager.AddTrackController ..> javafx.stage.FileChooser
it.unisa.java_music_playlist_manager.AddTrackController ..> javafx.stage.Stage
it.unisa.java_music_playlist_manager.AddTrackController ..> org.controlsfx.control.CheckComboBox
it.unisa.java_music_playlist_manager.AddTrackController ..> it.unisa.java_music_playlist_manager.model.TagPredefined
it.unisa.java_music_playlist_manager.AddTrackController ..> it.unisa.java_music_playlist_manager.model.Observer
it.unisa.java_music_playlist_manager.AddTrackController ..> it.unisa.java_music_playlist_manager.model.Tag
it.unisa.java_music_playlist_manager.App ..> java.lang.Override
it.unisa.java_music_playlist_manager.App ..> java.io.IOException
it.unisa.java_music_playlist_manager.App --|> javafx.application.Application
it.unisa.java_music_playlist_manager.App ..> javafx.fxml.FXMLLoader
it.unisa.java_music_playlist_manager.App ..> javafx.scene.Parent
it.unisa.java_music_playlist_manager.App ..> javafx.scene.Scene
it.unisa.java_music_playlist_manager.App ..> javafx.scene.image.Image
it.unisa.java_music_playlist_manager.App ..> javafx.stage.Stage
it.unisa.java_music_playlist_manager.HomeController ..> it.unisa.java_music_playlist_manager.model.Playlist
it.unisa.java_music_playlist_manager.HomeController ..> java.lang.Override
it.unisa.java_music_playlist_manager.HomeController ..> javafx.fxml.FXML
it.unisa.java_music_playlist_manager.HomeController ..> it.unisa.java_music_playlist_manager.model.Library
it.unisa.java_music_playlist_manager.HomeController ..> it.unisa.java_music_playlist_manager.model.Track
it.unisa.java_music_playlist_manager.HomeController ..> java.util.Comparator
it.unisa.java_music_playlist_manager.HomeController ..> java.util.List
it.unisa.java_music_playlist_manager.HomeController ..> javafx.beans.property.SimpleIntegerProperty
it.unisa.java_music_playlist_manager.HomeController ..> javafx.beans.property.SimpleStringProperty
it.unisa.java_music_playlist_manager.HomeController ..> javafx.collections.FXCollections
it.unisa.java_music_playlist_manager.HomeController ..> javafx.collections.ObservableList
it.unisa.java_music_playlist_manager.HomeController ..> javafx.scene.control.Label
it.unisa.java_music_playlist_manager.HomeController ..> javafx.scene.control.TableColumn
it.unisa.java_music_playlist_manager.HomeController ..> javafx.scene.control.TableView
it.unisa.java_music_playlist_manager.HomeController --|> it.unisa.java_music_playlist_manager.model.Observer
it.unisa.java_music_playlist_manager.PlayerController ..> java.lang.Override
it.unisa.java_music_playlist_manager.PlayerController ..> javafx.fxml.FXML
it.unisa.java_music_playlist_manager.PlayerController ..> it.unisa.java_music_playlist_manager.model.PlaybackManager
it.unisa.java_music_playlist_manager.PlayerController ..> it.unisa.java_music_playlist_manager.model.ShuffleStrategy
it.unisa.java_music_playlist_manager.PlayerController ..> it.unisa.java_music_playlist_manager.model.Track
it.unisa.java_music_playlist_manager.PlayerController ..> javafx.scene.control.Button
it.unisa.java_music_playlist_manager.PlayerController ..> javafx.scene.control.Label
it.unisa.java_music_playlist_manager.PlayerController ..> javafx.scene.control.Slider
it.unisa.java_music_playlist_manager.PlayerController ..> javafx.scene.image.ImageView
it.unisa.java_music_playlist_manager.PlayerController ..> javafx.scene.media.MediaPlayer
it.unisa.java_music_playlist_manager.PlayerController ..> javafx.util.Duration
it.unisa.java_music_playlist_manager.PlayerController --|> it.unisa.java_music_playlist_manager.model.Observer
it.unisa.java_music_playlist_manager.PrimaryViewController ..> it.unisa.java_music_playlist_manager.model.Playlist
it.unisa.java_music_playlist_manager.PrimaryViewController ..> it.unisa.java_music_playlist_manager.model.PlaylistGenerator
it.unisa.java_music_playlist_manager.PrimaryViewController ..> java.lang.Override
it.unisa.java_music_playlist_manager.PrimaryViewController ..> java.lang.SuppressWarnings
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.fxml.FXML
it.unisa.java_music_playlist_manager.PrimaryViewController ..> it.unisa.java_music_playlist_manager.model.AutomaticPlaylistGenerator
it.unisa.java_music_playlist_manager.PrimaryViewController ..> it.unisa.java_music_playlist_manager.model.Library
it.unisa.java_music_playlist_manager.PrimaryViewController ..> it.unisa.java_music_playlist_manager.model.ManualPlaylistGenerator
it.unisa.java_music_playlist_manager.PrimaryViewController ..> it.unisa.java_music_playlist_manager.model.PlaybackManager
it.unisa.java_music_playlist_manager.PrimaryViewController ..> it.unisa.java_music_playlist_manager.model.Track
it.unisa.java_music_playlist_manager.PrimaryViewController ..> java.io.IOException
it.unisa.java_music_playlist_manager.PrimaryViewController ..> java.util.ArrayList
it.unisa.java_music_playlist_manager.PrimaryViewController ..> java.util.HashSet
it.unisa.java_music_playlist_manager.PrimaryViewController ..> java.util.List
it.unisa.java_music_playlist_manager.PrimaryViewController ..> java.util.Locale
it.unisa.java_music_playlist_manager.PrimaryViewController ..> java.util.Optional
it.unisa.java_music_playlist_manager.PrimaryViewController ..> java.util.Set
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.beans.property.SimpleIntegerProperty
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.beans.property.SimpleStringProperty
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.collections.FXCollections
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.collections.ObservableList
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.fxml.FXMLLoader
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.Node
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.Parent
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.Scene
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.Alert
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.Button
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.ButtonType
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.ChoiceDialog
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.ComboBox
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.ContextMenu
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.Label
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.ListCell
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.ListView
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.MenuItem
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.ScrollPane
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.TableCell
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.TableColumn
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.TableView
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.TextInputDialog
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.control.Tooltip
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.scene.layout.HBox
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.stage.Modality
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.stage.Stage
it.unisa.java_music_playlist_manager.PrimaryViewController --|> it.unisa.java_music_playlist_manager.model.Observer
it.unisa.java_music_playlist_manager.PrimaryViewController ..> it.unisa.java_music_playlist_manager.model.Playable
it.unisa.java_music_playlist_manager.PrimaryViewController ..> it.unisa.java_music_playlist_manager.model.Tag
it.unisa.java_music_playlist_manager.SidebarController ..> javafx.fxml.FXML
it.unisa.java_music_playlist_manager.SidebarController ..> java.util.function.Consumer
it.unisa.java_music_playlist_manager.SidebarController ..> javafx.scene.control.Button
it.unisa.java_music_playlist_manager.SidebarController ..> javafx.scene.control.TextField
it.unisa.java_music_playlist_manager.model.AutomaticPlaylistByGenre --|> it.unisa.java_music_playlist_manager.model.Playlist
it.unisa.java_music_playlist_manager.model.AutomaticPlaylistByGenre ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.AutomaticPlaylistByGenre ..> java.util.List
it.unisa.java_music_playlist_manager.model.AutomaticPlaylistByGenre ..> java.util.stream.Collectors
it.unisa.java_music_playlist_manager.model.AutomaticPlaylistByTag --|> it.unisa.java_music_playlist_manager.model.Playlist
it.unisa.java_music_playlist_manager.model.AutomaticPlaylistByTag ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.AutomaticPlaylistByTag ..> java.util.List
it.unisa.java_music_playlist_manager.model.AutomaticPlaylistByTag ..> java.util.stream.Collectors
it.unisa.java_music_playlist_manager.model.AutomaticPlaylistByYear --|> it.unisa.java_music_playlist_manager.model.Playlist
it.unisa.java_music_playlist_manager.model.AutomaticPlaylistByYear ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.AutomaticPlaylistByYear ..> java.util.List
it.unisa.java_music_playlist_manager.model.AutomaticPlaylistByYear ..> java.util.stream.Collectors
it.unisa.java_music_playlist_manager.model.AutomaticPlaylistGenerator --|> it.unisa.java_music_playlist_manager.model.PlaylistGenerator
it.unisa.java_music_playlist_manager.model.AutomaticPlaylistGenerator ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.Library ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.Library ..> java.util.ArrayList
it.unisa.java_music_playlist_manager.model.Library ..> java.util.List
it.unisa.java_music_playlist_manager.model.Library --|> it.unisa.java_music_playlist_manager.model.Subject
it.unisa.java_music_playlist_manager.model.ManualPlaylist --|> it.unisa.java_music_playlist_manager.model.Playlist
it.unisa.java_music_playlist_manager.model.ManualPlaylist ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.ManualPlaylist ..> java.util.ArrayList
it.unisa.java_music_playlist_manager.model.ManualPlaylist ..> java.util.List
it.unisa.java_music_playlist_manager.model.ManualPlaylistGenerator --|> it.unisa.java_music_playlist_manager.model.PlaylistGenerator
it.unisa.java_music_playlist_manager.model.ManualPlaylistGenerator ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.PausedState ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.PausedState --|> it.unisa.java_music_playlist_manager.model.PlaybackState
it.unisa.java_music_playlist_manager.model.PlaybackManager ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.PlaybackManager ..> java.io.File
it.unisa.java_music_playlist_manager.model.PlaybackManager ..> java.util.ArrayList
it.unisa.java_music_playlist_manager.model.PlaybackManager ..> java.util.List
it.unisa.java_music_playlist_manager.model.PlaybackManager ..> javafx.scene.media.Media
it.unisa.java_music_playlist_manager.model.PlaybackManager ..> javafx.scene.media.MediaPlayer
it.unisa.java_music_playlist_manager.model.PlaybackManager --|> it.unisa.java_music_playlist_manager.model.Subject
it.unisa.java_music_playlist_manager.model.PlayingState ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.PlayingState --|> it.unisa.java_music_playlist_manager.model.PlaybackState
it.unisa.java_music_playlist_manager.model.RepeatStrategy ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.RepeatStrategy --|> it.unisa.java_music_playlist_manager.model.PlaybackStrategy
it.unisa.java_music_playlist_manager.model.RepeatTrackStrategy ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.RepeatTrackStrategy --|> it.unisa.java_music_playlist_manager.model.PlaybackStrategy
it.unisa.java_music_playlist_manager.model.SequentialStrategy ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.SequentialStrategy --|> it.unisa.java_music_playlist_manager.model.PlaybackStrategy
it.unisa.java_music_playlist_manager.model.ShuffleStrategy ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.ShuffleStrategy ..> java.util.ArrayList
it.unisa.java_music_playlist_manager.model.ShuffleStrategy ..> java.util.Collections
it.unisa.java_music_playlist_manager.model.ShuffleStrategy ..> java.util.List
it.unisa.java_music_playlist_manager.model.ShuffleStrategy --|> it.unisa.java_music_playlist_manager.model.PlaybackStrategy
it.unisa.java_music_playlist_manager.model.StoppedState ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.StoppedState --|> it.unisa.java_music_playlist_manager.model.PlaybackState
it.unisa.java_music_playlist_manager.model.Track ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.Track ..> java.time.LocalDate
it.unisa.java_music_playlist_manager.model.Track ..> java.util.ArrayList
it.unisa.java_music_playlist_manager.model.Track ..> java.util.Collections
it.unisa.java_music_playlist_manager.model.Track ..> java.util.LinkedHashSet
it.unisa.java_music_playlist_manager.model.Track ..> java.util.List
it.unisa.java_music_playlist_manager.model.Track ..> java.util.Objects
it.unisa.java_music_playlist_manager.model.Track ..> java.util.Set
it.unisa.java_music_playlist_manager.model.Track ..> java.util.UUID
it.unisa.java_music_playlist_manager.model.Track --|> it.unisa.java_music_playlist_manager.model.Playable
it.unisa.java_music_playlist_manager.model.Track --|> it.unisa.java_music_playlist_manager.model.Subject
it.unisa.java_music_playlist_manager.model.TagPredefined ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.TagPredefined --|> it.unisa.java_music_playlist_manager.model.Tag
it.unisa.java_music_playlist_manager.model.Playable ..> java.util.List
@enduml