@startuml
annotation java.lang.Override
annotation java.lang.SuppressWarnings
annotation javafx.fxml.FXML
class it.unisa.java_music_playlist_manager.AddTrackController
class it.unisa.java_music_playlist_manager.App
class it.unisa.java_music_playlist_manager.PlayerController
class it.unisa.java_music_playlist_manager.PrimaryViewController
class it.unisa.java_music_playlist_manager.SidebarController
class it.unisa.java_music_playlist_manager.model.AutomaticPlaylist
class it.unisa.java_music_playlist_manager.model.Library
class it.unisa.java_music_playlist_manager.model.PausedState
class it.unisa.java_music_playlist_manager.model.PlaybackManager
class it.unisa.java_music_playlist_manager.model.PlayingState
class it.unisa.java_music_playlist_manager.model.Playlist
class it.unisa.java_music_playlist_manager.model.PlaylistGenerator
class it.unisa.java_music_playlist_manager.model.RepeatStrategy
class it.unisa.java_music_playlist_manager.model.RepeatTrackStrategy
class it.unisa.java_music_playlist_manager.model.SequentialStrategy
class it.unisa.java_music_playlist_manager.model.ShuffleStrategy
class it.unisa.java_music_playlist_manager.model.StoppedState
class it.unisa.java_music_playlist_manager.model.TagCustomizable
class it.unisa.java_music_playlist_manager.model.TestDataLoader
class it.unisa.java_music_playlist_manager.model.Track
class java.io.File
class java.io.IOException
class java.nio.file.Files
class java.nio.file.Paths
class java.time.LocalDate
class java.util.ArrayList
class java.util.Collections
class java.util.HashSet
class java.util.LinkedHashSet
class java.util.List
class java.util.Objects
class java.util.Optional
class java.util.Set
class java.util.UUID
class java.util.function.Consumer
class java.util.regex.Matcher
class java.util.regex.Pattern
class java.util.stream.Collectors
class javafx.application.Application
class javafx.application.Platform
class javafx.beans.property.SimpleIntegerProperty
class javafx.beans.property.SimpleStringProperty
class javafx.collections.FXCollections
class javafx.collections.MapChangeListener
class javafx.collections.ObservableList
class javafx.fxml.FXMLLoader
class javafx.scene.Parent
class javafx.scene.Scene
class javafx.scene.control.Alert
class javafx.scene.control.Button
class javafx.scene.control.ButtonType
class javafx.scene.control.ChoiceDialog
class javafx.scene.control.ComboBox
class javafx.scene.control.ContextMenu
class javafx.scene.control.Label
class javafx.scene.control.ListCell
class javafx.scene.control.ListView
class javafx.scene.control.MenuItem
class javafx.scene.control.Slider
class javafx.scene.control.TableColumn
class javafx.scene.control.TableView
class javafx.scene.control.TextField
class javafx.scene.control.TextInputDialog
class javafx.scene.image.Image
class javafx.scene.image.ImageView
class javafx.scene.layout.HBox
class javafx.scene.layout.VBox
class javafx.scene.media.Media
class javafx.scene.media.MediaPlayer
class javafx.stage.FileChooser
class javafx.stage.Modality
class javafx.stage.Stage
class javafx.util.Duration
class org.controlsfx.control.CheckComboBox
enum it.unisa.java_music_playlist_manager.model.TagPredefined
interface it.unisa.java_music_playlist_manager.model.Observer
interface it.unisa.java_music_playlist_manager.model.Playable
interface it.unisa.java_music_playlist_manager.model.PlaybackState
interface it.unisa.java_music_playlist_manager.model.PlaybackStrategy
interface it.unisa.java_music_playlist_manager.model.Subject
interface it.unisa.java_music_playlist_manager.model.Tag
it.unisa.java_music_playlist_manager.AddTrackController ..> javafx.fxml.FXML
it.unisa.java_music_playlist_manager.App ..> java.lang.Override
it.unisa.java_music_playlist_manager.App --|> javafx.application.Application
it.unisa.java_music_playlist_manager.PlayerController ..> java.lang.Override
it.unisa.java_music_playlist_manager.PlayerController ..> javafx.fxml.FXML
it.unisa.java_music_playlist_manager.PrimaryViewController ..> java.lang.Override
it.unisa.java_music_playlist_manager.PrimaryViewController ..> java.lang.SuppressWarnings
it.unisa.java_music_playlist_manager.PrimaryViewController ..> javafx.fxml.FXML
it.unisa.java_music_playlist_manager.SidebarController ..> javafx.fxml.FXML
it.unisa.java_music_playlist_manager.model.AutomaticPlaylist ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.AutomaticPlaylist --|> it.unisa.java_music_playlist_manager.model.Playlist
it.unisa.java_music_playlist_manager.model.Library ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.PausedState ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.PlaybackManager ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.PlayingState ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.Playlist ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.RepeatStrategy ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.RepeatTrackStrategy ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.SequentialStrategy ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.ShuffleStrategy ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.StoppedState ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.TagCustomizable ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.Track ..> java.lang.Override
it.unisa.java_music_playlist_manager.model.TagPredefined ..> java.lang.Override
@enduml